# Generated by Django 4.0.2 on 2022-02-03 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_classroom_building_floor_classroom_floor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'edificio'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'piso'},
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='building',
        ),
        migrations.AlterField(
            model_name='floor',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='backend.building', verbose_name='edificio'),
        ),
    ]
