# Generated by Django 4.0.2 on 2022-02-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_building_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'profesór',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'turno',
            },
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'salon', 'verbose_name_plural': 'salones'},
        ),
    ]
