# Generated by Django 4.0.2 on 2022-02-03 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_professortype_shift_alter_classroom_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=125, verbose_name='apellidos')),
                ('number_id', models.CharField(max_length=14, verbose_name='número de cédula')),
                ('address', models.TextField(max_length=255, verbose_name='dirección')),
                ('phone_number', models.CharField(max_length=8, verbose_name='número de teléfono')),
                ('date_of_bird', models.DateField(verbose_name='fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'estudiante',
            },
        ),
        migrations.AlterModelOptions(
            name='professortype',
            options={'verbose_name': 'tipo de profesór', 'verbose_name_plural': 'tipos de profesóres'},
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=125, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=125, verbose_name='apellidos')),
                ('number_id', models.CharField(max_length=14, verbose_name='número de cédula')),
                ('address', models.TextField(max_length=255, verbose_name='dirección')),
                ('phone_number', models.CharField(max_length=8, verbose_name='número de teléfono')),
                ('date_of_bird', models.DateField(verbose_name='fecha de nacimiento')),
                ('professor_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.professortype', verbose_name='tipo de profesór')),
            ],
            options={
                'verbose_name': 'profesor',
                'verbose_name_plural': 'profesores',
            },
        ),
    ]
