# Generated by Django 4.0.2 on 2022-02-05 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_course_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.program', verbose_name='carrera')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.student', verbose_name='estudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('grade', models.IntegerField(default=0, verbose_name='nota')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.enrollment', verbose_name='matricula')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
