# Generated by Django 4.0.2 on 2022-02-05 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_enrollment_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.course', verbose_name='curso'),
        ),
    ]
