# Generated by Django 4.0.2 on 2022-02-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_program_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='precio del curso'),
        ),
    ]
