# Generated by Django 4.0.2 on 2022-02-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_course_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.AddField(
            model_name='course',
            name='weeks',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='duracción en semanas del curso'),
        ),
    ]
