# Generated by Django 4.0.2 on 2022-02-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_course_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.IntegerField(default=0, verbose_name='notas del curso'),
        ),
    ]
